### PR TITLE
Refactor the cache to live at the Source level

### PR DESCRIPTION
**Pull request by DavidS-om**
After moving the cache bulk of the cache lookup code into sdpcache (see https://github.com/overmindtech/sdpcache/pull/64), this change now shifts the cache into the individual sources. There is a new `CachingSource` interface that provides access to the cache. The SourceHost functions as dispatcher for Start/Stop/Purge at the engine level.

Sources that want caching of their queries need to implement CachingSource and provide a `sdpcache.Cache` instance on request.

All of this is to allow the source to access the cache locally when calling into itself.

Requires https://github.com/overmindtech/sdpcache/pull/64

### CODE REVIEW

**Comment by DavidS-om** [comment]
Looking at the necessary changes at the source level, I still need to decide whether to
* leave this as it is and have sources use the cache only when they're doing internal calls (less work for source authors, but potentially confusing since the cache is mostly operated outside the source)
* make the cache completely a implementation detail of the source (and thus remove all Lookup functionality here)
* provide a caching wrapper for sources that can be injected somewhere (but how would sources access that cache on demand)

Also
* create a engine-level cache for all sources that do not have a cache (would be good for rollout)

**Comment by dylanratcliffe** [comment]
There are a couple of use cases I see for this:

* **Smart invalidation:** for use-cases where the API being called allows things like "changed since" queries or "watch", having access to the cache could make our usage of the API much more efficient
* **Higher `SEARCH` hit-rate:** If a `SEARCH` query is doing mapping in the source (rather than passing the query directly to the API) then having the cache live in the source would allow for a better hit rate on searches
  * Would help: The AWS source which parses the ARN within the source then executes a GET
  * Wouldn't help: The K8s source which passes the search term to the API

In the smart invalidation case though, I struggle to see how having the cache store SDP items would more helpful than say implementing a source-specific cache that stores API query results, especially if a single items is made up of many API queries (like an S3 bucket or IAM role)

**Comment by DavidS-om** [comment]
Over the weekend I've convinced myself that the only workable way is to make the cache an implementation detail of the source. Some sources like all the meta sources do not need a cache and - as you point out - other sources may profit from custom (simpler or more optimized) cache implementations.

**Comment by dylanratcliffe** [comment]
Yeah I think you're right

**Comment by DavidS-om** [comment]
These last two were a bear to find.

Anyhoo, this is now ready to review. The tests are passing locally and require a sdpcache release ad go.mod update for github actions.

**Comment by DavidS-om** [comment]
the 8cpu runner drops `go vet` from 1m10s to 20s, and `go test` from 1m40s to 1m.

**Pull request merged**
